---
title: "CV"
author: "Robert C. Garrett"
email: rcg4@illinois.edu
output:
  pdf_document:
    latex_engine: pdflatex
    template: /mnt/c/Users/rcg4/garretrc.github.io/host/svm-latex-cv.tex
  html_document: default
fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 10.9pt
geometry: margin=1in
jobtitle: Statistics PhD Student
keywords: R Markdown, academic CV, template
linkcolor: blue
fontawesome: yes
phone: +330 998 5710
address: 200 S Vine Street, Urbana IL 61802
updated: no
urlcolor: blue
web: garretrc.github.io
---

```{r setup, include=FALSE}
#Sys.setenv(R_GSCMD = "/mnt/c/Program Files/gs/gs9.54.0/bin/gswin64c.exe")
knitr::opts_chunk$set(echo = TRUE)
```

\vspace{4mm}

**EDUCATION**  

*University of Illinois* Urbana, IL \hfill Third-Year Ph.D. Student, GPA: 3.88

- Working with advisor Bo Li while participating in the NSF-funded DIGI-MAT program, exploring connections between Statistics and atomic-scale Materials Science

- *Statistics Coursework*

    + Mathematical Statistics I, Mathematical Statistics II, Advanced Regression Analysis, Multivariate Analysis, Analysis of Variance, Sampling and Categorical Data, Measure Theory, Statistical Learning, Survival Data Analysis, Large Sample Theory, Applied Bayesian Modeling, Applied Stochastic Processes

***

*Miami University* Oxford, OH \hfill Graduated May 2019, GPA: 3.9

- B.S. in Mathematics & Statistics, Co-major in Predictive Analytics   
Minor in Computer Science

- *Statistics Coursework*

    + Statistical Modeling, Probability, Regression Analysis, Statistical Programming, Statistical Learning, Data Visualization, Inferential Statistics, Time Series, Bayesian Statistics, Statistical Consulting, Design of Experiments, Nonparameteric Statistics

- *Mathematics Coursework*

    + Calculus 1-3, Linear Algebra, Differential Equations, Abstract Algebra, Real Analysis, Numerical Analysis, Optimization

- *Computer Science Coursework*

    + Data Structures, Database Systems, Algorithms, Artificial Intelligence
    
- *Awards and Honors*

    + University Academic Scholars Program, Mathematics and Statistics Division (2015-2018), Dr. Donald C Weber Memorial Scholarship (2017 and 2018), Eric E Erickson Memorial Scholarship (2018), EY scholarship (2017)

***

**EXPERIENCE**

*Sandia National Labs* MARTIANS Student Intern \hfill May 2021-August 2021

- Applied Spatial Statistical methods to the study of fuel moisture for assessing wildfire risk.

*University of Illinois* DIGI-MAT Trainee \hfill August 2020-Present

- Participating in coursework, professional development, and collaboration with students and faculty in the Engineering, Physics, and Computer Science departments.

*University of Illinois* Teaching Assistant \hfill August 2019-May 2020

- Led weekly discussion meetings for undergraduate students in an introductory Mathematical Statistics course. Assisted with lecture and other course responsibilities.

*Cincinnati Children's Hospital* Department of Biostatistics and Epidemiology \hfill May 2018-July 2019

- Aggregated and visualized quarterly data on the progress of Pediatric Obesity patients at 30+ hospitals in the US as part of the Pediatric Obesity Weight Evaluation Registry (POWER) program.

*IBM* Research Triangle Park, NC \hfill May 2017-May 2018  

- Integrated cognitive tools including Watson Machine Learning, SPSS modeler, and R into blockchain networks in order to provide real-time analysis to users.

*Miami University* Undergraduate Associate \hfill January 2018-May 2019

- Assisted with teaching statistical methods and programming skills to undergraduate students in the Mathematical Statistics, Statistical Learning, and Statistical Modeling courses.

***

**RESEARCH PROJECTS AND COMPETITIONS**

- *Functional Data Methods for Comparing Climate Models*, University of Illinois 2021

    + Working with Dr. Trevor Harris and Dr. Bo Li to create a functional data method suitable for comparing high-dimensional spatio-temporal data. Focus on applications to climate model validation.

- *Bayesian Hierarchical Modeling for Toixcology Studies*, Miami University Spring 2019

    + Worked with Dr. Jing Zhang to jointly model both growth and survival outcomes in toxicology studies involving Fathead Minnows. Using a Bayesian hierarchical approach in STAN, we were able to adjust for the effect of using multiple tanks of fish at a given concentration level as well as mitigate the effect of survival bias on estimated growth effects.

- *2018 Joint Statistical Meetings*, Data Expo hosted by ASA Section on Statistical Computing

    + Worked with a team of 4 students to evaluate errors in National Weather Service forecasts using data from National Climatic Data Center weather stations. Work was broken down into two projects: extending the forecasts from the NWS data to all of the NCDC weather stations and comparing the performance of NWS forecasts to that of a naive data-centric approach.
    
    + For the data-centric model project, I used ridge regression along with a hull-based spatial variable selection approach to create new weather forecasts for each NCDC weather station.

- *2017 Joint Statistical Meetings*, Data Challenge hosted by ASA Government Section on Statistics

    + Worked with one other student to analyze the BLS Consumer Expenditure dataset. Focusing on the Great Recession, I modeled consumer budgeting habits using a compositional data approach. I presented our findings at the JSM, where we won third place in the Data Challenge.

- *2016 Joint Statistical Meetings*, Team Member

    + Worked with a team of 4 students to model car crash injuries using beta-binomial regression. I was the primary maintainer for the project's crash safety ratings database, which required using API calls and web scraping to gather the dataset and rigorous data cleaning to prepare the data for modeling.

- *ASA DataFest*, hosted by Miami University

    + 2019, First place - Measured rugby player fatigue using player tracking data
    + 2018, First place - Analyzed Indeed/US Census data with Voronoi diagrams
    + 2017, Third place - Visualized Expedia user behavior with Alluvial diagrams
    + 2016, First place - Created a network-based ad suggestion algorithm for Ticketmaster

***

**PUBLISHED PAPERS**

Cody R. Philips, Robert C. Garrett, Alan J. Tatro, & Thomas J. Fisher (2021). An analysis of crash-safety ratings and the true assessment of injuries by vehicle. Computational Statistics, 36(3), 1639–1660.

Garrett, R. C., Nar, A., Fisher, T. J., & Maurer, K., (2018). ggvoronoi: Voronoi Diagrams and Heatmaps with ggplot2. Journal of Open Source Software, 3(32), 1096, https://doi.org/10.21105/joss.01096

Schweitzer, B., Garrett, R. C. and Fisher, T. J.. 2018. An Analysis on the Accuracy of Weather Forecasts. In 2018 JSM Proceedings, Statistical Computing Section. Alexandria, VA: American Statistical Association.

Garrett, R. C. and Fisher, T. J.. 2017. An Analysis of Consumer Budgeting and the Great Recession. In 2017
JSM Proceedings. Alexandria, VA: American Statistical Association.

**PAPERS IN REVIEW**

Schweitzer, B., Rook, N., Garrett, R. C., & Fisher, T. J. (n.d.). A Spatial Extension of Weather Forecasts. Computational Statistics. Recommended for acceptance pending revisions as of November 7th, 2019.

Benjamin Schweitzer, Robert C. Garrett, Lydia Carter, Alison Tuiyott, Karsten T. Maurer, Thomas J. Fisher. An Analysis of the Impact of Rent Control on New York City Housing. Submitted to Computational Statistics as of February 28th, 2021.

Alison Tuiyott, Robert C. Garrett, Lydia Carter, Bejamin Schweitzer, Karsten T. Maurer, Thomas J. Fisher. Immigrant Residency and Happiness in New York City. Submitted to Computational Statistics as of February 22th, 2021.

**R PACKAGES**

Robert C. Garrett, Austin Nar, Thomas J. Fisher, Karsten Maurer. 2018. ggvoronoi: Voronoi Diagrams and
Heatmaps with 'ggplot2'. R package version 0.8.1. https://CRAN.R-project.org/package=ggvoronoi
